# This file was generated by GoReleaser. DO NOT EDIT.
cask "polyci" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "136a1bb416db656522a2e1efaa3897b08c66a8a4dc14f9c426d8bc4345818c7e"
      url "https://github.com/sqweyyy-create/PolyCI/releases/download/v#{version}/polyci_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c41193fbe6b2573de6f0a47fb183bd344df5ae6143ca9a6111163932d5e66e29"
      url "https://github.com/sqweyyy-create/PolyCI/releases/download/v#{version}/polyci_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2934cb31f2f6e999fead49509a9e13b0c321b540a3e90da76bb8eba2f62aba71"
      url "https://github.com/sqweyyy-create/PolyCI/releases/download/v#{version}/polyci_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0dfbab6ed1eea9de50564c30be9e14695014b9ea31671817af929fcbbdd3e1ed"
      url "https://github.com/sqweyyy-create/PolyCI/releases/download/v#{version}/polyci_linux_amd64.tar.gz"
    end
  end

  name "polyci"
  desc "Run CI/CD pipelines locally in Docker containers, with a debugger, across GitLab CI, CircleCI, and GitHub Actions"
  homepage "https://github.com/sqweyyy-create/PolyCI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "polyci"

  # No zap stanza required
end
