# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polyci < Formula
  desc "Run CI/CD pipelines locally in Docker containers, with a debugger, across GitLab CI, CircleCI, and GitHub Actions"
  homepage "https://github.com/sqweyyy-create/PolyCI"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sqweyyy-create/PolyCI/releases/download/v0.1.1/polyci_darwin_amd64.tar.gz"
      sha256 "1e15ecd8e78ec5da9d77bd7a5989e6f71c9acd553b3e6715437eaaa25b19b5be"

      define_method(:install) do
        bin.install "polyci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sqweyyy-create/PolyCI/releases/download/v0.1.1/polyci_darwin_arm64.tar.gz"
      sha256 "aa5f59041e72cbc0c7a66f4e4628e565c2b4c3ef3b4dc7702c7199afa7408079"

      define_method(:install) do
        bin.install "polyci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sqweyyy-create/PolyCI/releases/download/v0.1.1/polyci_linux_amd64.tar.gz"
      sha256 "25cfe318588d7d62a54f12101bffd87bc257c86fcff111fbf238875b044c4a54"
      define_method(:install) do
        bin.install "polyci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sqweyyy-create/PolyCI/releases/download/v0.1.1/polyci_linux_arm64.tar.gz"
      sha256 "aeb8e55d3e7055569d87d3ffd89458ace44c68cc907283cc812d932fdcd9bd01"
      define_method(:install) do
        bin.install "polyci"
      end
    end
  end

  test do
    system "#{bin}/polyci", "-h"
  end
end
